### ISSUE TITLE
Updates on Tech-stack used

### ISSUE THREAD

**Issue by Ericgacoki** [Jeffkent01coder/Intents#2]
It seems like the dimensions of the TextView are hard-coded
I highly recommend the use of viewBinding instead of the old findViewById 😂
Something else, I think working directly from the XML code creates a cleaner code than when working sorely from the design.

**Comment by Ericgacoki** [comment]
Hey @Jeffkent01coder, you should expect a PR soon!

**Comment by Jeffkent01coder** [comment]
And I must purpose to learn more
